remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Kasia Kowalczyk
logo: /assets/profile-pic.jpg
description: I am a final year PhD student at Imperial College London. I am interested in ultrafast processes in condensed matter. I have been working on high harmonic generation from wide-band gap dielectric crystals and on spectroscopy of liquid phase. 
